# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_user_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aboutme',
        ),
    ]
