# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_remove_user_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoURL',
            field=models.CharField(default='avatar-2.jpg', max_length=250),
            preserve_default=False,
        ),
    ]
