# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(help_text='conference id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of conference', max_length=20, unique=True)),
                ('acronym', models.CharField(help_text='acronym', max_length=20, unique=True)),
                ('city', models.CharField(help_text='Enter a city', max_length=200)),
                ('country_id', models.IntegerField(help_text='Enter a abstract')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contact_email', models.CharField(help_text='contact_emai', max_length=200)),
                ('webpage', models.CharField(help_text='webpage', max_length=200)),
                ('banner', models.CharField(help_text='banner', max_length=200)),
                ('license_expiry', models.CharField(help_text='status', max_length=200)),
                ('status', models.BooleanField(help_text='status', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(help_text='reviewer', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='user ID', max_length=20, unique=True)),
                ('track_id', models.IntegerField(help_text='track', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter a title', max_length=200)),
                ('abstract', models.TextField(help_text='Enter a abstract')),
                ('keywords', models.CharField(help_text='keywords', max_length=200)),
                ('paper_url', models.CharField(help_text='paper url', max_length=200)),
                ('status', models.CharField(help_text='status', max_length=200)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.conference')),
            ],
        ),
        migrations.DeleteModel(
            name='submissions',
        ),
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
            },
            bases=('default.user',),
        ),
    ]
