# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20170923_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='users',
            field=models.ManyToManyField(to='default.AuthorUser'),
        ),
    ]
