# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0019_auto_20170923_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.AlterField(
            model_name='author',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Submission'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Conference'),
        ),
    ]
