# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0021_auto_20170923_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='country code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Submission'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.Conference'),
        ),
    ]
